# Generated by Django 6.0.5 on 2026-05-23 20:28

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='discount_percent',
        ),
        migrations.AddField(
            model_name='promocode',
            name='discount_type',
            field=models.CharField(choices=[('PERCENT', 'Відсоток (%)'), ('FIXED', 'Сума в гривнях (грн)')], default='PERCENT', max_length=10, verbose_name='Тип знижки'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='value',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Значення знижки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Діє з'),
        ),
    ]
