# Generated by Django 6.0.5 on 2026-05-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва жанру')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва гри')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('release_date', models.DateField(verbose_name='Дата виходу')),
                ('developer', models.CharField(max_length=255, verbose_name='Розробник')),
                ('cover_image', models.ImageField(upload_to='games/covers/', verbose_name='Обкладинка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступна для продажу')),
                ('genres', models.ManyToManyField(related_name='games', to='games.genre', verbose_name='Жанри')),
            ],
        ),
    ]
