# Generated by Django 6.0.5 on 2026-05-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='age_rating',
            field=models.CharField(choices=[('0+', '0+ (Для всіх)'), ('6+', '6+'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+ (Дорослі)')], default='0+', max_length=5, verbose_name='Віковий рейтинг'),
        ),
    ]
