# Generated by Django 6.0.5 on 2026-05-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='license_key',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ключ активації'),
        ),
    ]
