# Generated by Django 6.0.5 on 2026-05-23 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_age_rating'),
        ('orders', '0003_orderitem_license_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.game'),
        ),
    ]
